// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5YDGRA69MpTev0YQ0ZoEihgEmPGYOHOQ',
    appId: '1:697573464945:web:80409876c69f464c19b4d0',
    messagingSenderId: '697573464945',
    projectId: 'smart-class-checkin-app',
    authDomain: 'smart-class-checkin-app.firebaseapp.com',
    storageBucket: 'smart-class-checkin-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpNpn-IWpMWa3MsxaphtykV6aUhiguk8',
    appId: '1:697573464945:android:8cd2be842e27e31619b4d0',
    messagingSenderId: '697573464945',
    projectId: 'smart-class-checkin-app',
    storageBucket: 'smart-class-checkin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIfhnjs89F_cOISgzr36i7MevW2fqvv-k',
    appId: '1:697573464945:ios:0e74e98a4265757419b4d0',
    messagingSenderId: '697573464945',
    projectId: 'smart-class-checkin-app',
    storageBucket: 'smart-class-checkin-app.firebasestorage.app',
    iosBundleId: 'com.example.smartClassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIfhnjs89F_cOISgzr36i7MevW2fqvv-k',
    appId: '1:697573464945:ios:0e74e98a4265757419b4d0',
    messagingSenderId: '697573464945',
    projectId: 'smart-class-checkin-app',
    storageBucket: 'smart-class-checkin-app.firebasestorage.app',
    iosBundleId: 'com.example.smartClassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5YDGRA69MpTev0YQ0ZoEihgEmPGYOHOQ',
    appId: '1:697573464945:web:43700fe3a84731f219b4d0',
    messagingSenderId: '697573464945',
    projectId: 'smart-class-checkin-app',
    authDomain: 'smart-class-checkin-app.firebaseapp.com',
    storageBucket: 'smart-class-checkin-app.firebasestorage.app',
  );
}
